// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMJ0hA1SqvlQ5chXRJuCvp986yQJdkUE',
    appId: '1:777512485750:android:62c3ac3e86a7b202e6b057',
    messagingSenderId: '777512485750',
    projectId: 'admin-decd9',
    databaseURL:
        'https://admin-decd9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-decd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZ-kh-QiLD0q6ZQelR5ss2CnkhuadL5E',
    appId: '1:777512485750:ios:794ff0d3e072d9b9e6b057',
    messagingSenderId: '777512485750',
    projectId: 'admin-decd9',
    databaseURL:
        'https://admin-decd9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-decd9.firebasestorage.app',
    iosBundleId: 'com.slfm.salesman',
  );
}
